services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_annonces
      MYSQL_USER: appuser
      MYSQL_PASSWORD: userpwd
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3006:3306"
    volumes:
      - db_data:/var/lib/data
      - ./backend/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

  backend:
    build: ./backend
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: db_annonces
      MYSQL_USER: appuser
      MYSQL_PASSWORD: userpwd
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data: